// 任务图标：精选一组线条图标，没选时按标题关键词自动匹配
import {
  Baby,
  Bed,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Camera,
  Car,
  Circle,
  Clapperboard,
  Code,
  Coffee,
  Dog,
  Dumbbell,
  Flower2,
  Footprints,
  Gamepad2,
  GraduationCap,
  Guitar,
  Heart,
  House,
  Languages,
  Laptop,
  Leaf,
  ListChecks,
  Mail,
  MessageCircle,
  Mountain,
  Music,
  NotebookPen,
  Package,
  Palette,
  PenLine,
  PenTool,
  Phone,
  Pill,
  Plane,
  Presentation,
  ShoppingBag,
  ShowerHead,
  Sparkles,
  Sunrise,
  Target,
  Trophy,
  Users,
  Utensils,
  Wallet,
  type LucideIcon
} from 'lucide-react'

export const TASK_ICONS: Record<string, LucideIcon> = {
  Circle,
  Code,
  Laptop,
  Briefcase,
  Users,
  Presentation,
  Mail,
  MessageCircle,
  Phone,
  PenLine,
  NotebookPen,
  BookOpen,
  GraduationCap,
  Languages,
  Brain,
  ListChecks,
  Target,
  Dumbbell,
  Footprints,
  Bike,
  Mountain,
  Heart,
  Pill,
  Bed,
  Coffee,
  Utensils,
  ShoppingBag,
  Package,
  Wallet,
  House,
  ShowerHead,
  Car,
  Plane,
  Music,
  Guitar,
  Clapperboard,
  Gamepad2,
  Camera,
  Palette,
  PenTool,
  Flower2,
  Leaf,
  Dog,
  Baby,
  Trophy,
  Sparkles,
  Sunrise
}

const RULES: [RegExp, string][] = [
  [/代码|编程|开发|写码|code|bug|调试|提交|部署/i, 'Code'],
  [/会议|周会|例会|开会|讨论|面试|评审/, 'Users'],
  [/汇报|演示|答辩|分享|讲/, 'Presentation'],
  [/邮件|mail/i, 'Mail'],
  [/消息|回复|聊天|微信|群/, 'MessageCircle'],
  [/电话|打给|通话/, 'Phone'],
  [/日记|笔记|复盘|记录/, 'NotebookPen'],
  [/写作|写|文章|稿|报告|论文/, 'PenLine'],
  [/阅读|读书|看书|读/, 'BookOpen'],
  [/课|学习|复习|考试|作业|网课/, 'GraduationCap'],
  [/单词|英语|日语|外语|背/, 'Languages'],
  [/算法|刷题|leetcode|思考|题/i, 'Brain'],
  [/计划|规划|整理|清单|待办/, 'ListChecks'],
  [/目标|冲刺/, 'Target'],
  [/健身|力量|锻炼|运动|训练|瑜伽/, 'Dumbbell'],
  [/跑步|散步|走路|步/, 'Footprints'],
  [/骑行|单车/, 'Bike'],
  [/徒步|爬山|登山/, 'Mountain'],
  [/药|医|牙|体检/, 'Pill'],
  [/睡|午休|休息|小憩/, 'Bed'],
  [/咖啡|茶/, 'Coffee'],
  [/吃|饭|餐|做菜|早饭|午饭|晚饭/, 'Utensils'],
  [/买|购物|超市/, 'ShoppingBag'],
  [/快递|取件|寄/, 'Package'],
  [/账|钱|缴费|报销|理财/, 'Wallet'],
  [/家务|打扫|收拾|房间/, 'House'],
  [/洗澡|洗漱/, 'ShowerHead'],
  [/开车|通勤|接送/, 'Car'],
  [/出差|航班|飞/, 'Plane'],
  [/音乐|听歌|歌/, 'Music'],
  [/吉他|钢琴|练琴|乐器/, 'Guitar'],
  [/电影|视频|追剧|看剧/, 'Clapperboard'],
  [/游戏|打游戏/, 'Gamepad2'],
  [/拍照|摄影/, 'Camera'],
  [/画|设计|绘/, 'Palette'],
  [/浇花|花|植物/, 'Flower2'],
  [/遛狗|猫|狗|宠物/, 'Dog'],
  [/孩子|宝宝/, 'Baby']
]

export function guessIcon(title: string): string {
  for (const [re, name] of RULES) if (re.test(title)) return name
  return 'Circle'
}

export const iconOf = (task: { icon?: string | null; title: string }): string =>
  task.icon && TASK_ICONS[task.icon] ? task.icon : guessIcon(task.title)

export function TaskIcon(props: { name: string; size?: number; className?: string }): React.JSX.Element {
  const Icon = TASK_ICONS[props.name] ?? Circle
  return <Icon size={props.size ?? 14} strokeWidth={2} className={props.className ?? 'ticon'} aria-hidden />
}
